// <auto-generated />
using JgLibDataModel;
using JgLibHelper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace JgLibDataModel.Migrations
{
    [DbContext(typeof(JgMaschineDb))]
    partial class JgMaschineDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JgLibDataModel.TabBediener", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Aenderung");

                    b.Property<byte[]>("Modifikation")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Nachname");

                    b.Property<string>("Vorname");

                    b.HasKey("Id");

                    b.ToTable("TabBedienerSet");
                });

            modelBuilder.Entity("JgLibDataModel.TabMaschine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Aenderung");

                    b.Property<Guid>("FStandort");

                    b.Property<string>("IpAdresse");

                    b.Property<string>("MaschineName");

                    b.Property<int>("MaschinenArt");

                    b.Property<byte[]>("Modifikation")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Port");

                    b.HasKey("Id");

                    b.HasIndex("FStandort");

                    b.ToTable("TabMaschineSet");
                });

            modelBuilder.Entity("JgLibDataModel.TabStandort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Aenderung");

                    b.Property<byte[]>("Modifikation")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("StandortName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TabStandortSet");
                });

            modelBuilder.Entity("JgLibDataModel.TabMaschine", b =>
                {
                    b.HasOne("JgLibDataModel.TabStandort", "EStandort")
                        .WithMany("SKfzEinsatz")
                        .HasForeignKey("FStandort")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
